#!/bin/bash

set -e

if [[ $EUID -eq 0 ]]; then
    echo -e "\033[0;31m! This is not designed to be run as root.\033[0;37m"
    exit 1
fi

if [[ $OSTYPE == "linux-gnu" ]]; then
    EA_PATH=${XDG_DATA_HOME:-$HOME/.local/share}/emacs_anywhere
else
    EA_PATH=$HOME/.emacs_anywhere
fi

EA_URL='https://github.com/zachcurry/emacs-anywhere.git'

err () { echo -e "Error: $@" 1>&2; }

installed () { hash $1 &> /dev/null; }

require_deps () {
    for d in $@; do
        if installed $d ; then
            echo -e "\033[0;32m  ✓ dependency check passed: $d\033[0;37m"
        else
            err dependency check failed: "'$d'" not found
            exit 1
        fi
    done
}

echo "> Checking dependancies"

case $OSTYPE in
    "darwin"*)
        WRKFLW_PATH=$EA_PATH/Emacs\ Anywhere.workflow
        SERVICES_PATH=$HOME/Library/Services
        ;;
    "linux-gnu")
        require_deps xclip xdotool xprop xwininfo
        ;;
    *)
        err OS $OSTYPE isn\'t currently supported
        exit 1
        ;;
esac

require_deps emacsclient git

if [ -a $EA_PATH ]; then
    echo -e '\033[0;33m> Uninstalling existing installation...\033[0;37m'
    rm -rf $EA_PATH
    echo '> Reinstalling Emacs Anywhere...'
else
    echo "> Installing Emacs Anywhere..."
fi

echo -e '\033[0;90m'
git clone $EA_URL $EA_PATH
echo -e '\033[0;37m'

if [[ $OSTYPE == "darwin"* ]]; then
    echo "> Copying $WRKFLW_PATH to ${SERVICES_PATH}..."
    cp -Rf "${WRKFLW_PATH}" $SERVICES_PATH
elif [[ $OSTYPE == "linux-gnu" ]]; then
    EA_EXEC=${XDG_BIN_HOME:-$HOME/.local/bin}/emacs_anywhere
    echo -e "> Symlinking executable to \033[0;34m$EA_EXEC\033[0;37m"
    ln -sf $EA_PATH/bin/linux $EA_EXEC
fi

echo -e '\033[0;32mEmacs Anywhere has been installed!\033[0;37m'
