#!/bin/bash

set -e

if [[ $OSTYPE == "linux-gnu" ]]; then
    EA_PATH=${XDG_DATA_HOME:-$HOME/.local/share}/emacs_anywhere
else
    EA_PATH=$HOME/.emacs_anywhere
fi

err () { echo -e "\033[0;31m! $@\033[0;37m" 1>&2; }

if [ ! -d $EA_PATH ]; then
    err Emacs Anywhere is not installed!
    exit 1
fi

pushd $EA_PATH > /dev/null
echo -ne '\033[0;90m'
git remote update
echo -ne '\033[0;37m'
LAST_UPDATE=`git show --no-notes --format=format:"%H" master | head -n 1`
LAST_COMMIT=`git show --no-notes --format=format:"%H" origin/master | head -n 1`

if [ $LAST_COMMIT != $LAST_UPDATE ]; then
        git pull origin master
        git pull --no-edit
        echo -e '\033[0;32mEmacs Anywhere has been updated!\033[0;37m'
        if [[ $OSTYPE == "darwin"* ]]; then
            cp -Rf $EA_PATH/Emacs\ Anywhere.workflow $HOME/Library/Services
        fi
else
    echo "No updates available"
fi
popd > /dev/null
