#!/bin/bash

set -e

if [[ $OSTYPE == "linux-gnu" ]]; then
    EA_PATH=${XDG_DATA_HOME:-$HOME/.local/share}/emacs_anywhere
else
    EA_PATH=$HOME/.emacs_anywhere
fi

err () { echo -e "\033[0;31m! $@\033[0;37m" 1>&2; }

if [ ! -d $EA_PATH ]; then
    err Emacs Anywhere is not installed!
    exit 1
fi

pushd $EA_PATH
git pull origin master
popd

if [[ $OSTYPE == "darwin"* ]]; then
    cp -Rf $EA_PATH/Emacs\ Anywhere.workflow $HOME/Library/Services
fi

echo Emacs Anywhere has been updated!
